version: "3.9"

networks:
  adminer_full:
  # laral_project_api_app_laravel_workspace_api_shared:
    # external: true

services: 
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8080:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - redis
      - mysql
      - mailhog
    container_name: adminer_full_server
    networks:
      - adminer_full
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html:delegated
      # - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
      # - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      # - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
      #- ./src:/usr/local/etc/php/php.ini
    container_name: php
    networks:
      - adminer_full
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: mysql
    env_file: 
      - ./env/mysql.env
    networks:
      - adminer_full
    volumes:
      - /opt/mysql_data:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - adminer_full
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./src:/var/www/html
    depends_on:
      - php  
    networks:
      - adminer_full
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - mysql
    networks:
      - adminer_full
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8890:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - adminer_full
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - adminer_full
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html
    networks:
      - adminer_full
